ALTER TABLE public.projects ADD COLUMN IF NOT EXISTS "defaultBgColor" TEXT DEFAULT 'default';
ALTER TABLE public.variations ADD COLUMN IF NOT EXISTS "imageScale" NUMERIC DEFAULT 1;

-- Fix for RLS policy on projects & variations (since we use backend password protection)
DROP POLICY IF EXISTS "Allow public all on projects" ON public.projects;
CREATE POLICY "Allow public all on projects" ON public.projects FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public all on variations" ON public.variations;
CREATE POLICY "Allow public all on variations" ON public.variations FOR ALL USING (true) WITH CHECK (true);

-- Fix for storage uploads (if it hasn't been added yet)
DROP POLICY IF EXISTS "Allow public uploads" ON storage.objects;
CREATE POLICY "Allow public uploads" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'uploads');

-- Create Categories Table
CREATE TABLE IF NOT EXISTS public.categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public all on categories" ON public.categories;
CREATE POLICY "Allow public all on categories" ON public.categories FOR ALL USING (true) WITH CHECK (true);

-- Insert default categories if not exists
INSERT INTO public.categories (name)
VALUES ('Logo'), ('Afiş'), ('Poster'), ('İllüstrasyonlar')
ON CONFLICT (name) DO NOTHING;
