-- Supabase SQL Schema
-- Run this entire script in the Supabase SQL Editor

-- 1. Create Projects Table
CREATE TABLE IF NOT EXISTS public.projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  category TEXT NOT NULL,
  description TEXT,
  "isMulti" BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create Variations Table 
CREATE TABLE IF NOT EXISTS public.variations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "projectId" BIGINT NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
  image TEXT NOT NULL,
  "colorCode" TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Set up Row Level Security (RLS) policies
-- We'll allow public READ access, but require authentication (or service role) for WRITE access.
-- Since the frontend handles auth using a simple password match to an env variable,
-- we can bypass RLS for inserts/updates by using the Supabase Service Role Key in the backend.

ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.variations ENABLE ROW LEVEL SECURITY;

-- Allow public read access to projects
CREATE POLICY "Public profiles are viewable by everyone."
  ON public.projects FOR SELECT
  USING ( true );

-- Allow public read access to variations
CREATE POLICY "Public variations are viewable by everyone."
  ON public.variations FOR SELECT
  USING ( true );

-- (Optional) If you want to insert the initial data directly via SQL:
/*
INSERT INTO public.projects (title, category, description, "isMulti") VALUES 
('Minimalist Kahve Markası', 'Logo Tasarımı', 'Modern ve sade bir kahve dükkanı için logo tasarımı.', true),
('Teknoloji Zirvesi', 'Afiş Tasarımı', 'Yıllık düzenlenen teknoloji zirvesi için ana afiş tasarımı.', true),
('Mimarlık Ofisi', 'Logo Tasarımı', '', false),
('Caz Konseri', 'Afiş Tasarımı', '', false);

-- You'd need to manually lookup the IDs to insert variations, example:
-- INSERT INTO public.variations ("projectId", image, "colorCode") VALUES (1, 'https://picsum.photos/seed/logo1a/1200/800', '#eab308');
*/
